version: '3.8'
services:
  db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev
  # html:
  #   image: html
  #   environment:
  #     - apiPath=http://api:3333
  #   ports:
  #     - '8080:3334'
  api:
    image: api
    environment:
      - DATABASE_URL="postgresql://dev:dev@localhost:5434/dev?schema=public"
    ports:
      - '8081:3333'
