version: '3.8'
services:
  larpcalendar_dev_db:
    image: postgres:13
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev
    networks:
      - larpcalendar_dev
  larpcalendar_test_db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    networks:
      - larpcalendar_test
networks:
  larpcalendar_dev:
  larpcalendar_test:
