version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev
    networks:
      - larpcalendar
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    networks:
      - larpcalendar
networks:
  larpcalendar:
